source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'


target 'VMSMobileSDK' do
  use_frameworks! :linkage => :static
  pod 'Alamofire', '~> 4.8.2'
	pod 'TweetNacl', '~> 1.0.0'
	pod 'CryptoSwift', '~> 1.0'
  pod 'CocoaAsyncSocket'
    
    target 'VMSMobileSDKTests' do
          inherit! :search_paths
          # Pods for product testing, if any
       end
end
